global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: temporal_metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: []
    metrics_path: /metrics

  - job_name: phoenix_metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: []
    metrics_path: /metrics
