location: eastus2
resourceGroup: Zenlabs-Agent-Foundry
type: Microsoft.App/containerApps
name: unified-dash-prometheus
properties:
  environmentId: /subscriptions/bc978289-ba91-4be9-8eee-82dc18f9cde9/resourceGroups/Zenlabs-Agent-Foundry/providers/Microsoft.App/managedEnvironments/zaf-aca-pvt-env
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false
      targetPort: 9090
      transport: http
    registries:
      - server: zafacr-gqfyc3h8eya2djey.azurecr.io
        username: zafacr
        passwordSecretRef: acr-password
    secrets:
      - name: acr-password
        value: "FKZSP1v13KwyQk4qPIJSJaIZ1Sx1xkASfp1ZnBwN5YmzAdmtHzskJQQJ99CBACHYHv6Eqg7NAAACAZCRoXHy"
  template:
    replicas:
      min: 1
      max: 1
    containers:
      - name: prometheus
        image: zafacr-gqfyc3h8eya2djey.azurecr.io/unified-dash/prometheus:latest
        resources:
          cpu: 0.25
          memory: 0.5Gi
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention.time=7d"
